### ISSUE TITLE
How to catch the initialization exception?

### ISSUE THREAD

**Issue by kelicto** [postsharp/PostSharp.Samples#15]
I want to tell user a friendly message to replace not catched excetpion.

**Comment by prochan2** [comment]
Hello @kelicto , thank you for getting in touch. This channel serves for issues related to the published PostSharp samples in this repository. For general questions, please use either https://stackoverflow.com/ , where you mark your question with the `PostSharp` tag or, if you are a commercial customer, you may also use our support forum at https://support.postsharp.net/. In either case, please specify the kind of your app (WPF/WinForms/Console/Razor/...), what exactly you mean by "initialization exception" in the context of the platform, and the required form of the message shown to the user. (Message-box/...)

**Comment by kelicto** [comment]
Thanks!
