### ISSUE TITLE
Suggestion: Add Blazor support

### ISSUE THREAD

**Issue by DiomedesDominguez** [postsharp/PostSharp.Samples#8]
This may be late, but since I didn't find samples of PostSharp in Blazor I assume that there isn't support at all. I recently read about MVVM Support in Blazor and noticed that with PostSharp we can have (finally) a stable version after a long waiting. Here is the link I read https://blog.jeremylikness.com/blog/2019-01-04_mvvm-support-in-blazor/.

**Comment by HonzaSinkora** [comment]
We are waiting for the mono project to address an issue that we had during testing of Blazor with PostSharp. This is the ticket: [18740](https://github.com/mono/mono/issues/18740).

I'm hoping that they will fix this before Blazor goes stable. Blazor Server seems to be working fine with PostSharp.
